### ISSUE TITLE
Fault URL formation for operations

### ISSUE THREAD

**Issue by AkshayGuleria** [DustinGrau-PSC/CatalogViewer#1]
The URL formed for operations is faulty and requesting any data does not work.
Ex: 
Catalog URL:- http://oemobiledemo.progress.com/CustomerService/static/CustomerService.json
Operation Details
READ [GET]
https:////rest/MobilityDemoService/dsCustomer?filter={filter}

Error captured from browser's inspect view :
```OPTIONS https://rest/MobilityDemoService/dsCustomer?filter={%22filter%22:%22Custnum=1%22}&{} net::ERR_NAME_NOT_RESOLVED jquery-1.12.4.min.js:4 ```

**Comment by DustinGrau-PSC** [comment]
The catalog URL provided does not resolve to a usable file, nor does the target of your GET appear to be something that can be resolved without use of a local hosts file or DNS entry.

Looking at the OEMobileDemo site the following appear to be current and valid catalogs:
http://oemobiledemo.progress.com/OEMobileDemoServices/static/SemanticTypesService.json
http://oemobiledemo.progress.com/OEMobileDemoServices/static/EmployeeSubmit.json

However, it appears that any attempt to utilize these services results in a 401 "Unauthorized" response. I do not see, nor am I aware, of the security model in use with these services, but you would need to authenticate if this is the response returned. Please note that this program does not make use of any CORS options, and is ideally meant to run against a local service on the same domain, not across domains.

**Comment by AkshayGuleria** [comment]
Thanks for the clarification @DustinGrau-PSC. Sorry for closing this soon late.
